export const MENU = [
  {
    type: 'Pizza',
    name: 'Sarda',
    categories: ['Spicy'],
    ingredients: ['mozzarella', 'pecorino cheese', 'spicy salami'],
    price: 9,
    image: 'Images/sarda.jpeg',
    quantity: 1,
  },
  {
    type: 'Pizza',
    name: 'Pizza Romana',
    categories: [],
    ingredients: ['mozzarella', 'anchovies', 'capers', 'oregano'],
    price: 9,
    image: 'Images/Pizza-Romana-1-800x477.jpeg',
    quantity: 1,
  },
  {
    type: 'Pizza',
    name: 'Pizza Napoletana',
    categories: ['Vegetarian'],
    ingredients: ['mozzarella', 'tomato', 'oregano'],
    price: 8,
    image: 'Images/napoletana.jpeg',
    quantity: 1,
  },
  {
    type: 'Pizza',
    name: 'Four seasons pizza',
    categories: ['Comfort food'],
    ingredients: ['artichokes', 'tomatoes', 'basil', 'mushrooms', 'ham'],
    price: 11,
    image: 'Images/four-seasons-pizza.jpeg',
    quantity: 1,
  },
  {
    type: 'Pasta',
    name: 'Pasta Carbonara',
    categories: ['Comfort food'],
    ingredients: ['egg', 'lardons', 'Pecorino romano'],
    price: 8,
    image: 'Images/pasta-carbonara_b-864x413.jpeg',
    quantity: 1,
  },
  {
    type: 'Pasta',
    name: 'Spaghetti bolognese',
    categories: ['Comfort food'],
    ingredients: ['beef', 'chopped tomatoes', 'garlic'],
    price: 8,
    image: 'Images/bolognaise.jpeg',
    quantity: 1,
  },
  {
    type: 'Pasta',
    name: 'Lasagna bolognese',
    categories: ['Comfort food'],
    ingredients: ['mozzarella', 'tomato', 'beef'],
    price: 10,
    image: 'Images/lasagna-bolognese.jpeg',
    quantity: 1,
  },
  {
    type: 'Pasta',
    name: 'Cacio e pepe',
    categories: ['Vegetarian'],
    ingredients: ['pecorino romano', 'black pepper'],
    price: 9,
    image: 'Images/Spaghetti-Cacio-e-Pepe-Pecorino-and-black-pepper-spaghetti_1200x800.jpeg',
    quantity: 1,
  },

  {
    type: 'Desserts',
    name: 'Torrone Semifreddo',
    categories: ['Desserts', 'Vegetarian'],
    ingredients: ['honey', 'egg whites', 'nuts'],
    price: 4,
    image: 'Images/Torrone Semifreddo.jpeg',
    quantity: 1,
  },
  {
    type: 'Desserts',
    name: 'Mixed-Nut-Milk Panna Cotta',
    categories: ['Desserts', 'Vegetarian'],
    ingredients: ['nut milk', 'honey', 'strawberry jam'],
    price: 10,
    image: 'Images/pannacotta.jpeg',
    quantity: 1,
  },
  {
    type: 'Desserts',
    name: 'Chocolate and Pistachio Biscotti',
    categories: ['Desserts', 'Vegetarian'],
    ingredients: ['dark chocolate', 'egg', 'nuts'],
    price: 9,
    image: 'Images/biscotti.jpeg',
    quantity: 1,
  },
];
